name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test
        run: mvn clean verify

  dockerize:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t lab1-app .
          docker tag lab1-app ${{ secrets.DOCKER_USERNAME }}/lab1-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/lab1-app:latest
